baseURL: /
languageCode: en-us
defaultContentLanguage: en
title: tedshd's DevNote
theme: hugo-theme-okayish-blog
copyright: © 2020 Tedshd
googleAnalytics: UA-49247550-2
disqusShortname: tedshd
enableGitInfo: true
hasCJKLanguage: true
paginate: 2
staticDir: static

params:
# These will be used for OpenGraph, Twitter Card and Schema.org
  description: Develop & Design Note by Ted
  images: ['https://s3.amazonaws.com/logdown-production/system/blog/3202/og_image/logdown.png']
  avatar: https://graph.facebook.com/100004089951579/picture?type=large
  themecolor: #607d8b

  # This is the number of terms within a taxonomy per page
  termsPaginate: 50
  # Enable/disable share links (Facebook, Twitter and LinkedIn)
  shareLinksEnabled: false
  # Enable/disable Google Analytics in local server
  gaLocalEnabled: false

taxonomies:
  category: "categories"
  tag: "tags"

# Add `author` under `[taxonomies]` as below
# so that you can provide metadata for each author
#
# See: https://gohugo.io/content-management/taxonomies/#add-custom-metadata-to-a-taxonomy-term
  author: Tedshd

# Add menu items to the navigation bar as below.
# N.B. Use identifiers as the keys for translations.

menu:
  main:
  - identifier: "categories"
    name: "Categories"
    url: "/categories"
  - identifier: "tags"
    name: "tags"
    url: "/tags"
  sub:
  - identifier: "Github"
    name: "Github"
    url: "https://github.com/tedshd"

  - identifier: "Linkedin"
    name: "Linkedin"
    url: "https://tw.linkedin.com/in/tedshd"

  - identifier: "Blog"
    name: "Blog"
    url: "http://tysh310246.blogspot.tw/"

  - identifier: "Facebook"
    name: "Facebook"
    url: "https://www.facebook.com/chander.shiu"

  - identifier: "About"
    name: "About"
    url: "http://tedshd.github.io/resume/"
