baseURL = "https://blog.tedshd.io"
languageCode = "en-us"
theme = "anubis2"
title = "Tedshd's Dev note"

[author]
name = "Tedshd"

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/Categories"
weight = 3

[params]
social = [
    { id="github", name="tedshd" },
    { id="linkedin", url="https://tw.linkedin.com/in/tedshd" },
    { id="facebook", url="https://www.facebook.com/chander.shiu" }
]
rssIcon = false